/**
 * Custom Monaco Editor Themes
 * Replicates popular Ace Editor themes for Monaco
 */

var customThemes = {
  monokai: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '75715E', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'F92672' },
      { token: 'keyword.control', foreground: 'F92672' },
      { token: 'keyword.operator', foreground: 'F92672' },
      { token: 'string', foreground: 'E6DB74' },
      { token: 'string.escape', foreground: 'AE81FF' },
      { token: 'number', foreground: 'AE81FF' },
      { token: 'constant', foreground: 'AE81FF' },
      { token: 'constant.language', foreground: 'AE81FF' },
      { token: 'type', foreground: '66D9EF', fontStyle: 'italic' },
      { token: 'type.identifier', foreground: 'A6E22E' },
      { token: 'class', foreground: 'A6E22E' },
      { token: 'function', foreground: 'A6E22E' },
      { token: 'function.declaration', foreground: 'A6E22E' },
      { token: 'variable', foreground: 'F8F8F2' },
      { token: 'variable.parameter', foreground: 'FD971F', fontStyle: 'italic' },
      { token: 'tag', foreground: 'F92672' },
      { token: 'tag.attribute.name', foreground: 'A6E22E' },
      { token: 'attribute.name', foreground: 'A6E22E' },
      { token: 'attribute.value', foreground: 'E6DB74' },
      { token: 'delimiter', foreground: 'F8F8F2' },
      { token: 'delimiter.bracket', foreground: 'F8F8F2' },
      { token: 'operator', foreground: 'F92672' },
      { token: 'identifier', foreground: 'F8F8F2' },
      { token: 'regexp', foreground: 'E6DB74' },
      /* SAIL tokens */
      { token: 'keyword.function.system', foreground: 'F92672' },
      { token: 'keyword.function.standard', foreground: 'F92672' },
      { token: 'keyword.reference', foreground: 'F92672' },
      { token: 'keyword.constant', foreground: 'F92672' },
      { token: 'keyword.parameter', foreground: 'FD971F' },
      { token: 'keyword.variable', foreground: 'FD971F' },
      { token: 'function.system', foreground: 'A6E22E' },
      { token: 'function.standard', foreground: '66D9EF' },
      { token: 'function.reference', foreground: 'E6DB74' },
      { token: 'variable.property', foreground: 'A6E22E' }
    ],
    colors: {
      'editor.background': '#272822',
      'editor.foreground': '#F8F8F2',
      'editorCursor.foreground': '#F8F8F0',
      'editor.lineHighlightBackground': '#3E3D32',
      'editor.selectionBackground': '#49483E',
      'editor.selectionHighlightBackground': '#49483E88',
      'editorLineNumber.foreground': '#8F908A',
      'editorLineNumber.activeForeground': '#C2C2BF',
      'editorGutter.background': '#272822',
      'editorIndentGuide.background': '#464741',
      'editorIndentGuide.activeBackground': '#767771',
      'editorWhitespace.foreground': '#464741',
      'editorBracketMatch.background': '#3E3D3277',
      'editorBracketMatch.border': '#888888'
    }
  },

  dracula: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '6272A4', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'FF79C6' },
      { token: 'keyword.control', foreground: 'FF79C6' },
      { token: 'keyword.operator', foreground: 'FF79C6' },
      { token: 'string', foreground: 'F1FA8C' },
      { token: 'string.escape', foreground: 'FF79C6' },
      { token: 'number', foreground: 'BD93F9' },
      { token: 'constant', foreground: 'BD93F9' },
      { token: 'constant.language', foreground: 'BD93F9' },
      { token: 'type', foreground: '8BE9FD', fontStyle: 'italic' },
      { token: 'type.identifier', foreground: '8BE9FD' },
      { token: 'class', foreground: '8BE9FD' },
      { token: 'function', foreground: '50FA7B' },
      { token: 'function.declaration', foreground: '50FA7B' },
      { token: 'variable', foreground: 'F8F8F2' },
      { token: 'variable.parameter', foreground: 'FFB86C', fontStyle: 'italic' },
      { token: 'tag', foreground: 'FF79C6' },
      { token: 'tag.attribute.name', foreground: '50FA7B' },
      { token: 'attribute.name', foreground: '50FA7B' },
      { token: 'attribute.value', foreground: 'F1FA8C' },
      { token: 'delimiter', foreground: 'F8F8F2' },
      { token: 'operator', foreground: 'FF79C6' },
      { token: 'identifier', foreground: 'F8F8F2' },
      { token: 'regexp', foreground: 'F1FA8C' },
      /* SAIL tokens */
      { token: 'keyword.function.system', foreground: 'FF79C6' },
      { token: 'keyword.function.standard', foreground: 'FF79C6' },
      { token: 'keyword.reference', foreground: 'FF79C6' },
      { token: 'keyword.constant', foreground: 'FF79C6' },
      { token: 'keyword.parameter', foreground: 'FFB86C' },
      { token: 'keyword.variable', foreground: 'FFB86C' },
      { token: 'function.system', foreground: '50FA7B' },
      { token: 'function.standard', foreground: '8BE9FD' },
      { token: 'function.reference', foreground: 'F1FA8C' },
      { token: 'variable.property', foreground: '50FA7B' }
    ],
    colors: {
      'editor.background': '#282A36',
      'editor.foreground': '#F8F8F2',
      'editorCursor.foreground': '#F8F8F0',
      'editor.lineHighlightBackground': '#44475A',
      'editor.selectionBackground': '#44475A',
      'editor.selectionHighlightBackground': '#44475A88',
      'editorLineNumber.foreground': '#6272A4',
      'editorLineNumber.activeForeground': '#F8F8F2',
      'editorGutter.background': '#282A36',
      'editorIndentGuide.background': '#424450',
      'editorIndentGuide.activeBackground': '#6272A4',
      'editorWhitespace.foreground': '#424450',
      'editorBracketMatch.background': '#44475A77',
      'editorBracketMatch.border': '#F8F8F2'
    }
  },

  github: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '6A737D', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'D73A49' },
      { token: 'keyword.control', foreground: 'D73A49' },
      { token: 'keyword.operator', foreground: 'D73A49' },
      { token: 'string', foreground: '032F62' },
      { token: 'string.escape', foreground: '005CC5' },
      { token: 'number', foreground: '005CC5' },
      { token: 'constant', foreground: '005CC5' },
      { token: 'constant.language', foreground: '005CC5' },
      { token: 'type', foreground: '6F42C1' },
      { token: 'type.identifier', foreground: '6F42C1' },
      { token: 'class', foreground: '6F42C1' },
      { token: 'function', foreground: '6F42C1' },
      { token: 'function.declaration', foreground: '6F42C1' },
      { token: 'variable', foreground: '24292E' },
      { token: 'variable.parameter', foreground: 'E36209' },
      { token: 'tag', foreground: '22863A' },
      { token: 'tag.attribute.name', foreground: '6F42C1' },
      { token: 'attribute.name', foreground: '6F42C1' },
      { token: 'attribute.value', foreground: '032F62' },
      { token: 'delimiter', foreground: '24292E' },
      { token: 'operator', foreground: 'D73A49' },
      { token: 'identifier', foreground: '24292E' },
      { token: 'regexp', foreground: '032F62' },
      /* SAIL tokens */
      { token: 'keyword.function.system', foreground: 'D73A49' },
      { token: 'keyword.function.standard', foreground: 'D73A49' },
      { token: 'keyword.reference', foreground: 'D73A49' },
      { token: 'keyword.constant', foreground: 'D73A49' },
      { token: 'keyword.parameter', foreground: 'E36209' },
      { token: 'keyword.variable', foreground: 'E36209' },
      { token: 'function.system', foreground: '6F42C1' },
      { token: 'function.standard', foreground: '005CC5' },
      { token: 'function.reference', foreground: '22863A' },
      { token: 'variable.property', foreground: '6F42C1' }
    ],
    colors: {
      'editor.background': '#FFFFFF',
      'editor.foreground': '#24292E',
      'editorCursor.foreground': '#24292E',
      'editor.lineHighlightBackground': '#F6F8FA',
      'editor.selectionBackground': '#C8E1FF',
      'editor.selectionHighlightBackground': '#C8E1FF88',
      'editorLineNumber.foreground': '#959DA5',
      'editorLineNumber.activeForeground': '#24292E',
      'editorGutter.background': '#FFFFFF',
      'editorIndentGuide.background': '#E1E4E8',
      'editorIndentGuide.activeBackground': '#C8C8C8',
      'editorWhitespace.foreground': '#E1E4E8',
      'editorBracketMatch.background': '#C8E1FF77',
      'editorBracketMatch.border': '#005CC5'
    }
  },

  'solarized-dark': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '586E75', fontStyle: 'italic' },
      { token: 'keyword', foreground: '859900' },
      { token: 'keyword.control', foreground: '859900' },
      { token: 'keyword.operator', foreground: '859900' },
      { token: 'string', foreground: '2AA198' },
      { token: 'string.escape', foreground: 'CB4B16' },
      { token: 'number', foreground: 'D33682' },
      { token: 'constant', foreground: 'CB4B16' },
      { token: 'constant.language', foreground: 'CB4B16' },
      { token: 'type', foreground: 'B58900' },
      { token: 'type.identifier', foreground: 'B58900' },
      { token: 'class', foreground: 'B58900' },
      { token: 'function', foreground: '268BD2' },
      { token: 'function.declaration', foreground: '268BD2' },
      { token: 'variable', foreground: '839496' },
      { token: 'variable.parameter', foreground: 'CB4B16' },
      { token: 'tag', foreground: '268BD2' },
      { token: 'tag.attribute.name', foreground: '93A1A1' },
      { token: 'attribute.name', foreground: '93A1A1' },
      { token: 'attribute.value', foreground: '2AA198' },
      { token: 'delimiter', foreground: '839496' },
      { token: 'operator', foreground: '859900' },
      { token: 'identifier', foreground: '839496' },
      { token: 'regexp', foreground: 'DC322F' },
      /* SAIL tokens */
      { token: 'keyword.function.system', foreground: '859900' },
      { token: 'keyword.function.standard', foreground: '859900' },
      { token: 'keyword.reference', foreground: '859900' },
      { token: 'keyword.constant', foreground: '859900' },
      { token: 'keyword.parameter', foreground: 'CB4B16' },
      { token: 'keyword.variable', foreground: 'CB4B16' },
      { token: 'function.system', foreground: '268BD2' },
      { token: 'function.standard', foreground: '2AA198' },
      { token: 'function.reference', foreground: 'B58900' },
      { token: 'variable.property', foreground: '268BD2' }
    ],
    colors: {
      'editor.background': '#002B36',
      'editor.foreground': '#839496',
      'editorCursor.foreground': '#839496',
      'editor.lineHighlightBackground': '#073642',
      'editor.selectionBackground': '#073642',
      'editor.selectionHighlightBackground': '#07364288',
      'editorLineNumber.foreground': '#586E75',
      'editorLineNumber.activeForeground': '#839496',
      'editorGutter.background': '#002B36',
      'editorIndentGuide.background': '#073642',
      'editorIndentGuide.activeBackground': '#586E75',
      'editorWhitespace.foreground': '#073642',
      'editorBracketMatch.background': '#07364277',
      'editorBracketMatch.border': '#268BD2'
    }
  },

  'solarized-light': {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '93A1A1', fontStyle: 'italic' },
      { token: 'keyword', foreground: '859900' },
      { token: 'keyword.control', foreground: '859900' },
      { token: 'keyword.operator', foreground: '859900' },
      { token: 'string', foreground: '2AA198' },
      { token: 'string.escape', foreground: 'CB4B16' },
      { token: 'number', foreground: 'D33682' },
      { token: 'constant', foreground: 'CB4B16' },
      { token: 'constant.language', foreground: 'CB4B16' },
      { token: 'type', foreground: 'B58900' },
      { token: 'type.identifier', foreground: 'B58900' },
      { token: 'class', foreground: 'B58900' },
      { token: 'function', foreground: '268BD2' },
      { token: 'function.declaration', foreground: '268BD2' },
      { token: 'variable', foreground: '657B83' },
      { token: 'variable.parameter', foreground: 'CB4B16' },
      { token: 'tag', foreground: '268BD2' },
      { token: 'tag.attribute.name', foreground: '586E75' },
      { token: 'attribute.name', foreground: '586E75' },
      { token: 'attribute.value', foreground: '2AA198' },
      { token: 'delimiter', foreground: '657B83' },
      { token: 'operator', foreground: '859900' },
      { token: 'identifier', foreground: '657B83' },
      { token: 'regexp', foreground: 'DC322F' },
      /* SAIL tokens */
      { token: 'keyword.function.system', foreground: '859900' },
      { token: 'keyword.function.standard', foreground: '859900' },
      { token: 'keyword.reference', foreground: '859900' },
      { token: 'keyword.constant', foreground: '859900' },
      { token: 'keyword.parameter', foreground: 'CB4B16' },
      { token: 'keyword.variable', foreground: 'CB4B16' },
      { token: 'function.system', foreground: '268BD2' },
      { token: 'function.standard', foreground: '2AA198' },
      { token: 'function.reference', foreground: 'B58900' },
      { token: 'variable.property', foreground: '268BD2' }
    ],
    colors: {
      'editor.background': '#FDF6E3',
      'editor.foreground': '#657B83',
      'editorCursor.foreground': '#657B83',
      'editor.lineHighlightBackground': '#EEE8D5',
      'editor.selectionBackground': '#EEE8D5',
      'editor.selectionHighlightBackground': '#EEE8D588',
      'editorLineNumber.foreground': '#93A1A1',
      'editorLineNumber.activeForeground': '#657B83',
      'editorGutter.background': '#FDF6E3',
      'editorIndentGuide.background': '#EEE8D5',
      'editorIndentGuide.activeBackground': '#93A1A1',
      'editorWhitespace.foreground': '#EEE8D5',
      'editorBracketMatch.background': '#EEE8D577',
      'editorBracketMatch.border': '#268BD2'
    }
  },

  nord: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '616E88', fontStyle: 'italic' },
      { token: 'keyword', foreground: '81A1C1' },
      { token: 'keyword.control', foreground: '81A1C1' },
      { token: 'keyword.operator', foreground: '81A1C1' },
      { token: 'string', foreground: 'A3BE8C' },
      { token: 'string.escape', foreground: 'EBCB8B' },
      { token: 'number', foreground: 'B48EAD' },
      { token: 'constant', foreground: 'B48EAD' },
      { token: 'constant.language', foreground: '81A1C1' },
      { token: 'type', foreground: '8FBCBB' },
      { token: 'type.identifier', foreground: '8FBCBB' },
      { token: 'class', foreground: '8FBCBB' },
      { token: 'function', foreground: '88C0D0' },
      { token: 'function.declaration', foreground: '88C0D0' },
      { token: 'variable', foreground: 'D8DEE9' },
      { token: 'variable.parameter', foreground: 'D8DEE9' },
      { token: 'tag', foreground: '81A1C1' },
      { token: 'tag.attribute.name', foreground: '8FBCBB' },
      { token: 'attribute.name', foreground: '8FBCBB' },
      { token: 'attribute.value', foreground: 'A3BE8C' },
      { token: 'delimiter', foreground: 'ECEFF4' },
      { token: 'operator', foreground: '81A1C1' },
      { token: 'identifier', foreground: 'D8DEE9' },
      { token: 'regexp', foreground: 'EBCB8B' },
      /* SAIL tokens */
      { token: 'keyword.function.system', foreground: '81A1C1' },
      { token: 'keyword.function.standard', foreground: '81A1C1' },
      { token: 'keyword.reference', foreground: '81A1C1' },
      { token: 'keyword.constant', foreground: '81A1C1' },
      { token: 'keyword.parameter', foreground: 'EBCB8B' },
      { token: 'keyword.variable', foreground: 'EBCB8B' },
      { token: 'function.system', foreground: '88C0D0' },
      { token: 'function.standard', foreground: '8FBCBB' },
      { token: 'function.reference', foreground: 'A3BE8C' },
      { token: 'variable.property', foreground: '88C0D0' }
    ],
    colors: {
      'editor.background': '#2E3440',
      'editor.foreground': '#D8DEE9',
      'editorCursor.foreground': '#D8DEE9',
      'editor.lineHighlightBackground': '#3B4252',
      'editor.selectionBackground': '#434C5E',
      'editor.selectionHighlightBackground': '#434C5E88',
      'editorLineNumber.foreground': '#4C566A',
      'editorLineNumber.activeForeground': '#D8DEE9',
      'editorGutter.background': '#2E3440',
      'editorIndentGuide.background': '#434C5E',
      'editorIndentGuide.activeBackground': '#4C566A',
      'editorWhitespace.foreground': '#434C5E',
      'editorBracketMatch.background': '#434C5E77',
      'editorBracketMatch.border': '#88C0D0'
    }
  },

  'tomorrow-night': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '969896', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'B294BB' },
      { token: 'keyword.control', foreground: 'B294BB' },
      { token: 'keyword.operator', foreground: 'B294BB' },
      { token: 'string', foreground: 'B5BD68' },
      { token: 'string.escape', foreground: 'DE935F' },
      { token: 'number', foreground: 'DE935F' },
      { token: 'constant', foreground: 'DE935F' },
      { token: 'constant.language', foreground: 'DE935F' },
      { token: 'type', foreground: 'F0C674' },
      { token: 'type.identifier', foreground: 'F0C674' },
      { token: 'class', foreground: 'F0C674' },
      { token: 'function', foreground: '81A2BE' },
      { token: 'function.declaration', foreground: '81A2BE' },
      { token: 'variable', foreground: 'C5C8C6' },
      { token: 'variable.parameter', foreground: 'C5C8C6' },
      { token: 'tag', foreground: 'CC6666' },
      { token: 'tag.attribute.name', foreground: 'DE935F' },
      { token: 'attribute.name', foreground: 'DE935F' },
      { token: 'attribute.value', foreground: 'B5BD68' },
      { token: 'delimiter', foreground: 'C5C8C6' },
      { token: 'operator', foreground: '8ABEB7' },
      { token: 'identifier', foreground: 'C5C8C6' },
      { token: 'regexp', foreground: 'B5BD68' },
      /* SAIL tokens */
      { token: 'keyword.function.system', foreground: 'B294BB' },
      { token: 'keyword.function.standard', foreground: 'B294BB' },
      { token: 'keyword.reference', foreground: 'B294BB' },
      { token: 'keyword.constant', foreground: 'B294BB' },
      { token: 'keyword.parameter', foreground: 'DE935F' },
      { token: 'keyword.variable', foreground: 'DE935F' },
      { token: 'function.system', foreground: '81A2BE' },
      { token: 'function.standard', foreground: '8ABEB7' },
      { token: 'function.reference', foreground: 'F0C674' },
      { token: 'variable.property', foreground: '81A2BE' }
    ],
    colors: {
      'editor.background': '#1D1F21',
      'editor.foreground': '#C5C8C6',
      'editorCursor.foreground': '#AEAFAD',
      'editor.lineHighlightBackground': '#282A2E',
      'editor.selectionBackground': '#373B41',
      'editor.selectionHighlightBackground': '#373B4188',
      'editorLineNumber.foreground': '#969896',
      'editorLineNumber.activeForeground': '#C5C8C6',
      'editorGutter.background': '#1D1F21',
      'editorIndentGuide.background': '#373B41',
      'editorIndentGuide.activeBackground': '#969896',
      'editorWhitespace.foreground': '#373B41',
      'editorBracketMatch.background': '#373B4177',
      'editorBracketMatch.border': '#81A2BE'
    }
  },

  cobalt: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '0088FF', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'FF9D00' },
      { token: 'keyword.control', foreground: 'FF9D00' },
      { token: 'keyword.operator', foreground: 'FF9D00' },
      { token: 'string', foreground: '3AD900' },
      { token: 'string.escape', foreground: 'FF628C' },
      { token: 'number', foreground: 'FF628C' },
      { token: 'constant', foreground: 'FF628C' },
      { token: 'constant.language', foreground: 'FF628C' },
      { token: 'type', foreground: '80FFBB' },
      { token: 'type.identifier', foreground: '80FFBB' },
      { token: 'class', foreground: '80FFBB' },
      { token: 'function', foreground: 'FFEE80' },
      { token: 'function.declaration', foreground: 'FFEE80' },
      { token: 'variable', foreground: 'FFFFFF' },
      { token: 'variable.parameter', foreground: 'FFFFFF' },
      { token: 'tag', foreground: 'FF9D00' },
      { token: 'tag.attribute.name', foreground: 'FFEE80' },
      { token: 'attribute.name', foreground: 'FFEE80' },
      { token: 'attribute.value', foreground: '3AD900' },
      { token: 'delimiter', foreground: 'FFFFFF' },
      { token: 'operator', foreground: 'FF9D00' },
      { token: 'identifier', foreground: 'FFFFFF' },
      { token: 'regexp', foreground: '80FFBB' },
      /* SAIL tokens */
      { token: 'keyword.function.system', foreground: 'FF9D00' },
      { token: 'keyword.function.standard', foreground: 'FF9D00' },
      { token: 'keyword.reference', foreground: 'FF9D00' },
      { token: 'keyword.constant', foreground: 'FF9D00' },
      { token: 'keyword.parameter', foreground: 'FF628C' },
      { token: 'keyword.variable', foreground: 'FF628C' },
      { token: 'function.system', foreground: 'FFEE80' },
      { token: 'function.standard', foreground: '80FFBB' },
      { token: 'function.reference', foreground: '3AD900' },
      { token: 'variable.property', foreground: 'FFEE80' }
    ],
    colors: {
      'editor.background': '#002240',
      'editor.foreground': '#FFFFFF',
      'editorCursor.foreground': '#FFFFFF',
      'editor.lineHighlightBackground': '#002E52',
      'editor.selectionBackground': '#0050A4',
      'editor.selectionHighlightBackground': '#0050A488',
      'editorLineNumber.foreground': '#346BAD',
      'editorLineNumber.activeForeground': '#FFFFFF',
      'editorGutter.background': '#002240',
      'editorIndentGuide.background': '#004080',
      'editorIndentGuide.activeBackground': '#0088FF',
      'editorWhitespace.foreground': '#004080',
      'editorBracketMatch.background': '#0050A477',
      'editorBracketMatch.border': '#FF9D00'
    }
  },

  twilight: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '5F5A60', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'CDA869' },
      { token: 'keyword.control', foreground: 'CDA869' },
      { token: 'keyword.operator', foreground: 'CDA869' },
      { token: 'string', foreground: '8F9D6A' },
      { token: 'string.escape', foreground: 'CF6A4C' },
      { token: 'number', foreground: 'CF6A4C' },
      { token: 'constant', foreground: 'CF6A4C' },
      { token: 'constant.language', foreground: 'CF6A4C' },
      { token: 'type', foreground: '9B703F' },
      { token: 'type.identifier', foreground: '9B703F' },
      { token: 'class', foreground: '9B703F' },
      { token: 'function', foreground: '9B859D' },
      { token: 'function.declaration', foreground: '9B859D' },
      { token: 'variable', foreground: 'F8F8F8' },
      { token: 'variable.parameter', foreground: '7587A6' },
      { token: 'tag', foreground: 'CDA869' },
      { token: 'tag.attribute.name', foreground: '9B703F' },
      { token: 'attribute.name', foreground: '9B703F' },
      { token: 'attribute.value', foreground: '8F9D6A' },
      { token: 'delimiter', foreground: 'F8F8F8' },
      { token: 'operator', foreground: 'CDA869' },
      { token: 'identifier', foreground: 'F8F8F8' },
      { token: 'regexp', foreground: 'E9C062' },
      /* SAIL tokens */
      { token: 'keyword.function.system', foreground: 'CDA869' },
      { token: 'keyword.function.standard', foreground: 'CDA869' },
      { token: 'keyword.reference', foreground: 'CDA869' },
      { token: 'keyword.constant', foreground: 'CDA869' },
      { token: 'keyword.parameter', foreground: '7587A6' },
      { token: 'keyword.variable', foreground: '7587A6' },
      { token: 'function.system', foreground: '9B859D' },
      { token: 'function.standard', foreground: 'CF6A4C' },
      { token: 'function.reference', foreground: '8F9D6A' },
      { token: 'variable.property', foreground: '9B859D' }
    ],
    colors: {
      'editor.background': '#141414',
      'editor.foreground': '#F8F8F8',
      'editorCursor.foreground': '#A7A7A7',
      'editor.lineHighlightBackground': '#1F1F1F',
      'editor.selectionBackground': '#3A3A3A',
      'editor.selectionHighlightBackground': '#3A3A3A88',
      'editorLineNumber.foreground': '#5A5A5A',
      'editorLineNumber.activeForeground': '#F8F8F8',
      'editorGutter.background': '#141414',
      'editorIndentGuide.background': '#2A2A2A',
      'editorIndentGuide.activeBackground': '#5A5A5A',
      'editorWhitespace.foreground': '#2A2A2A',
      'editorBracketMatch.background': '#3A3A3A77',
      'editorBracketMatch.border': '#CDA869'
    }
  }
};

/**
 * Registers all custom themes with Monaco Editor
 * Call this after Monaco is loaded but before creating editors
 */
function registerCustomThemes() {
  Object.keys(customThemes).forEach(function(themeName) {
    monaco.editor.defineTheme(themeName, customThemes[themeName]);
  });
}
